### ISSUE TITLE
Connection Issues on MacOS Big Sur

### ISSUE THREAD

**Issue by harthorst** [PersoSim/de.persosim.simulator#95]
Hi,

I'm trying to use PersoSim on MacOS (Big Sur). My company uses a VPN which seems to interfere with PersoSim. I can't pair and PersoSim shows the following message:

Local server port: 54366
Exception in thread "Thread-5" java.lang.IllegalStateException: UDP announce failed
	at de.persosim.websocket.Announcer.run(Announcer.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Can't assign requested address
	at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at de.persosim.websocket.Announcer.run(Announcer.java:62)
	... 1 more

Java version is Adopt 11, tried Adopt 8 and Oracle JRE 8 as well

If I disable VPN I get this error:
Local server port: 51236
Exception in thread "Thread-5" java.lang.IllegalStateException: Reading of handshake message failed with exception
	at de.persosim.websocket.WebSocketProtocol.readToDelimiter(WebSocketProtocol.java:187)
	at de.persosim.websocket.WebSocketProtocol.handleHandshake(WebSocketProtocol.java:126)
	at de.persosim.websocket.WebSocketProtocol.handleConnection(WebSocketProtocol.java:47)
	at de.persosim.websocket.WebsocketComm.handleWebSocketCommunication(WebsocketComm.java:167)
	at de.persosim.websocket.WebsocketComm.run(WebsocketComm.java:135)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bouncycastle.tls.TlsNoCloseNotifyException: No close_notify alert received before connection closed
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.readApplicationData(Unknown Source)
	at org.bouncycastle.tls.TlsInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
	at java.io.InputStreamReader.read(InputStreamReader.java:168)
	at de.persosim.websocket.WebSocketProtocol.readToDelimiter(WebSocketProtocol.java:171)
	... 5 more

Any hints?

**Comment by hfunke** [comment]
Please use our new version 1.0.1 of PersoSim. This version runs with your Mac.
